server.port=8080
spring.application.name=gateway-server

# Register with Eureka and locate services
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Gateway Routing Rules
# Route to 'marcelo' microservice
spring.cloud.gateway.routes[0].id=marcelo-service
spring.cloud.gateway.routes[0].uri=lb://marcelo
spring.cloud.gateway.routes[0].predicates[0]=Path=/nombres/**

# Route to 'ontaneda' microservice
spring.cloud.gateway.routes[1].id=ontaneda-service
spring.cloud.gateway.routes[1].uri=lb://ontaneda
spring.cloud.gateway.routes[1].predicates[0]=Path=/apellidos/**
