server.port=8888
spring.application.name=config-server

# Config Server Git Repository Configuration (Local Repo)
spring.cloud.config.server.git.uri=file:///C:/Users/MARCELO/Downloads/exam2parcial/config-repo
spring.cloud.config.server.git.default-label=master

# Register con Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
