server.port=8888
spring.application.name=config-server

# Config Server Git Repository Configuration (Remote Public Repo)
# Reemplaza la siguiente URL con la URL HTTPS de tu repositorio de GitHub público
spring.cloud.config.server.git.uri=https://github.com/Marcelo234/microservicios_java.git
spring.cloud.config.server.git.default-label=main

# Register con Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
